### ISSUE TITLE
How to use column as dominant?

### ISSUE THREAD

**Issue by Nulligma** [PixelToast/flutter-boxy#13]
I want circleavatar's radius to be equal to the text column 

```
BoxyRow(
        children: [
          CircleAvatar(
            backgroundColor: Colors.white,
            child: Padding(
              padding: const EdgeInsets.all(5.0),
              child: CircleAvatar(
                backgroundImage: imageProvider,
              ),
            ),
          ),
          const SizedBox(width: 8),
          Dominant(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  authorName,
                  style: Theme.of(context)
                      .textTheme
                      .headline2!
                      .copyWith(color: Colors.black),
                ),
                Text(
                  title,
                  style: Theme.of(context)
                      .textTheme
                      .headline3!
                      .copyWith(color: Colors.black),
                )
              ],
            ),
          )
        ],
      ),
```

In the code above the circle avatar never takes radius of text column and defaults back to 20. but if I give radius some very large value like 100 then circle avatar never exceeded the boundary of the textcolumn.

**Comment by PixelToast** [comment]
I think this should work, assuming each text only has a maximum line length of 1:
https://gist.github.com/PixelToast/8cb3d913a19c496fb9511858990488b9

Resizing horizontally:

https://user-images.githubusercontent.com/2466461/153071042-31da87ac-11bb-4e75-b4fb-d17937a2544d.mp4

Changing text size w/ hot reload:

https://user-images.githubusercontent.com/2466461/153071090-f79b2f7e-67a7-4c36-8295-015ba38406aa.mp4

If the text needs to wrap I think you are SOL, there would be a circular dependency in sizing (size of text would depend on it's width, but its width would also depend on its height because more height reduces its remaining space).

**Comment by PixelToast** [comment]
I'm gonna close this one since its going stale
